<?php

namespace Container1wCfIxU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4x02bjVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4x02bjV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4x02bjV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commandRepository' => ['privates', 'App\\Repository\\CommandRepository', 'getCommandRepositoryService', true],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'quoteRequestRepository' => ['privates', 'App\\Repository\\QuoteRequestRepository', 'getQuoteRequestRepositoryService', true],
            'serviceRepository' => ['privates', 'App\\Repository\\ServiceRepository', 'getServiceRepositoryService', true],
            'usersRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'commandRepository' => 'App\\Repository\\CommandRepository',
            'productRepository' => 'App\\Repository\\ProductRepository',
            'quoteRequestRepository' => 'App\\Repository\\QuoteRequestRepository',
            'serviceRepository' => 'App\\Repository\\ServiceRepository',
            'usersRepository' => 'App\\Repository\\UsersRepository',
        ]);
    }
}
