<?php

namespace Container1wCfIxU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Mp_OhuaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Mp.Ohua' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Mp.Ohua'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'productCategoryRepository' => ['privates', 'App\\Repository\\ProductCategoryRepository', 'getProductCategoryRepositoryService', true],
        ], [
            'productCategoryRepository' => 'App\\Repository\\ProductCategoryRepository',
        ]);
    }
}
