<?php

namespace Container1wCfIxU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K6IOLDcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.K6IOLDc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.K6IOLDc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'mailerService' => ['privates', 'App\\Service\\MailerService', 'getMailerServiceService', true],
            'quoteRequest' => ['privates', '.errored..service_locator.K6IOLDc.App\\Entity\\QuoteRequest', NULL, 'Cannot autowire service ".service_locator.K6IOLDc": it needs an instance of "App\\Entity\\QuoteRequest" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'mailerService' => 'App\\Service\\MailerService',
            'quoteRequest' => 'App\\Entity\\QuoteRequest',
        ]);
    }
}
