<?php

namespace Container1wCfIxU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BYebD3GService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BYebD3G' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BYebD3G'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'command' => ['privates', '.errored..service_locator.BYebD3G.App\\Entity\\Command', NULL, 'Cannot autowire service ".service_locator.BYebD3G": it needs an instance of "App\\Entity\\Command" but this type has been excluded in "config/services.yaml".'],
        ], [
            'command' => 'App\\Entity\\Command',
        ]);
    }
}
