<?php

namespace Container1wCfIxU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Xgz24hXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xgz24hX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xgz24hX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'productCategory' => ['privates', 'App\\Repository\\ProductCategoryRepository', 'getProductCategoryRepositoryService', true],
            'productRepo' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
        ], [
            'productCategory' => 'App\\Repository\\ProductCategoryRepository',
            'productRepo' => 'App\\Repository\\ProductRepository',
        ]);
    }
}
