<?php

namespace Container1wCfIxU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C_5YtW9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C.5YtW9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C.5YtW9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'command' => ['privates', '.errored..service_locator.C.5YtW9.App\\Entity\\Command', NULL, 'Cannot autowire service ".service_locator.C.5YtW9": it needs an instance of "App\\Entity\\Command" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'command' => 'App\\Entity\\Command',
            'entityManager' => '?',
        ]);
    }
}
