<?php

namespace Container1wCfIxU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O_SCDVJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.o.SCDVJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o.SCDVJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'productCategory' => ['privates', '.errored..service_locator.o.SCDVJ.App\\Entity\\ProductCategory', NULL, 'Cannot autowire service ".service_locator.o.SCDVJ": it needs an instance of "App\\Entity\\ProductCategory" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'productCategory' => 'App\\Entity\\ProductCategory',
        ]);
    }
}
