<?php

namespace Container1wCfIxU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HytM1wzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hytM1wz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hytM1wz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commandRepository' => ['privates', 'App\\Repository\\CommandRepository', 'getCommandRepositoryService', true],
            'quoteRequestRepository' => ['privates', 'App\\Repository\\QuoteRequestRepository', 'getQuoteRequestRepositoryService', true],
        ], [
            'commandRepository' => 'App\\Repository\\CommandRepository',
            'quoteRequestRepository' => 'App\\Repository\\QuoteRequestRepository',
        ]);
    }
}
