<?php

namespace Container1wCfIxU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WImUEk2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wImUEk2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wImUEk2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'qrStatus' => ['privates', '.errored..service_locator.wImUEk2.App\\Entity\\QrStatus', NULL, 'Cannot autowire service ".service_locator.wImUEk2": it needs an instance of "App\\Entity\\QrStatus" but this type has been excluded in "config/services.yaml".'],
        ], [
            'qrStatus' => 'App\\Entity\\QrStatus',
        ]);
    }
}
