<?php

namespace Container1wCfIxU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AE1bcikService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AE1bcik' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AE1bcik'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'qrStatusRepository' => ['privates', 'App\\Repository\\QrStatusRepository', 'getQrStatusRepositoryService', true],
        ], [
            'qrStatusRepository' => 'App\\Repository\\QrStatusRepository',
        ]);
    }
}
