<?php

namespace Container1wCfIxU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateAdminCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CreateAdminCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\CreateAdminCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:create-admin', [], 'Add a short description for your command', false, #[\Closure(name: 'App\\Command\\CreateAdminCommand')] fn (): \App\Command\CreateAdminCommand => ($container->privates['App\\Command\\CreateAdminCommand'] ?? $container->load('getCreateAdminCommandService')));
    }
}
