<?php

namespace Container1wCfIxU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductCategory2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.o.SCDVJ.App\Entity\ProductCategory' shared service.
     *
     * @return \App\Entity\ProductCategory
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.o.SCDVJ": it needs an instance of "App\\Entity\\ProductCategory" but this type has been excluded in "config/services.yaml".');
    }
}
