<?php

namespace Container1wCfIxU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuoteRequest2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.EBJbCfO.App\Entity\QuoteRequest' shared service.
     *
     * @return \App\Entity\QuoteRequest
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.EBJbCfO": it needs an instance of "App\\Entity\\QuoteRequest" but this type has been excluded in "config/services.yaml".');
    }
}
