<?php

namespace Container1wCfIxU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationFormTypeProService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\RegistrationFormTypePro' shared autowired service.
     *
     * @return \App\Form\RegistrationFormTypePro
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/RegistrationFormTypePro.php';

        return $container->privates['App\\Form\\RegistrationFormTypePro'] = new \App\Form\RegistrationFormTypePro();
    }
}
