<?php

namespace Container1wCfIxU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRequestControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\RequestController' shared autowired service.
     *
     * @return \App\Controller\RequestController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/RequestController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/RequestService.php';

        $container->services['App\\Controller\\RequestController'] = $instance = new \App\Controller\RequestController(new \App\Service\RequestService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['App\\Repository\\ServiceRepository'] ?? $container->load('getServiceRepositoryService')), ($container->privates['App\\Repository\\QrStatusRepository'] ?? $container->load('getQrStatusRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\RequestController', $container));

        return $instance;
    }
}
